apiVersion: v1
kind: Service
metadata:
  name: eks-gitops-project
  namespace: eks-gitops-project
spec:
  selector:
    app: eks-gitops-project
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
