name: aks-gitops-project
on:
  push:
    branches:
      - branch2
  pull_request:
    branches:
      - branch2
jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: chekout repo
        uses: actions/checkout@v4
      # 2. install java
      - name: install java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # 3. test maven
      - name: test maven project
        working-directory: app
        run: mvn validate
      # 4. build/compile
      - name: build/compile
        working-directory: app
        run: mvn compile
